name: Publish Docker image

on:
  push:
    branches: ['main']


env:
  PROJECT_ID: ${{secrets.GKE_PROJECT_ID}}
  GKE_CLUSTER: autopilot-cluster-1
  GKE_ZONE: us-central1
  DEPLOYMENT_NAME: nodeappDeploy
  IMAGE: nodeapp
  TAG: latest

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Build and Push Docker Image
        run: |-
          docker build --tag "${{secrets.DOCKER_USERNAME}}/${{env.IMAGE}}:${{env.TAG}}" .
          docker push "${{secrets.DOCKER_USERNAME}}/${{env.IMAGE}}:${{env.TAG}}"

      - name: Setup Google Cloud CLI
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@0.1.3
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        with:
          service_account_key: ${{secrets.GKE_SERVICE_ACCOUNT_KEY}}
          project_id: ${{secrets.GKE_PROJECT_ID}}

      - name: Get GKE Credentials
        run: |-
          gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"
      
      - name: Set up Kustomize
        run: |-
          curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
          chmod u+x ./kustomize
          
      - name: Deploy Image to GKE cluster
        run: |-
          gcloud components install gke-gcloud-auth-plugin
          ./kustomize create deployment $DEPLOYMENT_NAME --image="docker.io/${{secrets.DOCKER_USERNAME}}/${{env.IMAGE}}:${{env.TAG}}"
          ./kustomize build . | kubectl apply -f -
          kubectl rollout status deployment/$DEPLOYMENT_NAME
          kubectl get services -o wide