name: Deploy to Minikube

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: build Node.js Docker Image and Deploy to minikube
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build Docker image
        run: docker build -t deploy-app .

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: |
          docker tag deploy-app ${{ secrets.DOCKER_USERNAME }}/deploy-app:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/deploy-app:${{ github.sha }}

      - name: Set up Kubernetes context
        uses: Azure/k8s-set-context@v1
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG }}

      - name: Deploy to Minikube
        run: kubectl apply -f deployment.yml

      - name: Create Service
        run: kubectl apply -f service.yml

      - name: Wait for deployment to be ready
        run: |
          while [[ $(kubectl get deployments deployment-nodeapp --output 'jsonpath={.status.readyReplicas}') != "1" ]]; do
            echo "Waiting for deployment to be ready..."
            sleep 10
          done

      - name: Test Service URLs
        run: minikube service list
