name: Deploy to GKE

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Configure Google Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GKE_PROJECT_ID }}
          service_account_email: ${{ secrets.GKE_SERVICE_ACCOUNT_EMAIL }}
          service_account_key: ${{ secrets.GKE_SERVICE_ACCOUNT_KEY }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: gcr.io/${{ secrets.GKE_PROJECT_ID }}/my-node-app:${{ github.sha }}

      - name: Deploy to GKE
        uses: google-github-actions/deploy-cloud-run@v0.5.0
        with:
          image: gcr.io/${{ secrets.GKE_PROJECT_ID }}/my-node-app:${{ github.sha }}
          platform: gke
          project_id: ${{ secrets.GKE_PROJECT_ID }}
          location: us-central1
          cluster: my-gke-cluster
          namespace: default
